FROM mysql:8.0
#mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
CMD ["mysqld", "--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci"]

#root password
ENV MYSQL_ROOT_PASSWORD password
#timeozne
ENV TZ Asia/Tokyo